spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schema_name
    username: "root"
    password: "123456"
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    out-of-order: true
    locations: classpath:db/migration
server:
  port: ${PORT:8080}