spring:
  datasource:
    url: jdbc:mysql://localhost:3306/
    username: "root"
    password: "admin"
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
server:
  port: ${PORT:8080}