server:
  port: ${PORT:8080}

logging:
  level:
    com.oocl.springbootviewpoint: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

spring:
  flyway:
    enabled: true
    locations: classpath:db/migration/common,classpath:db/migration/mysql
    baseline-on-migrate: true
    validate-on-migrate: true

kouzi:
  api:
    url: https://api.coze.cn/v3/chat?
    key: pat_YYDHIzVdqWVzwbLS3HlZITrMHJtEGI2SVOGNqp5gkWDc6GxF7O6KYM90zE4we10p
gaode:
  api:
    key: 4ef53442f20206b88a091ed644de9025