spring:
  jpa:
    show-sql: false

server:
  port: ${PORT:8080}
  compression:
    enabled: true
  http2:
    enabled: true

logging:
  level:
    com.oocl.springbootviewpoint: WARN
    org.springframework.web: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
  metrics:
    export:
      jmx:
        enabled: false
    enable:
      process: false
      system: false
      jvm: false
    binders:
      processor: false
      uptime: false
      jvm: false

kouzi:
  api:
    url: https://api.coze.cn/v3/chat?
    key: pat_YYDHIzVdqWVzwbLS3HlZITrMHJtEGI2SVOGNqp5gkWDc6GxF7O6KYM90zE4we10p
gaode:
  api:
    key: 4ef53442f20206b88a091ed644de9025