ALTER TABLE trip MODIFY COLUMN name VARCHAR(255) NULL;
ALTER TABLE trip MODIFY COLUMN start DATETIME NULL;
ALTER TABLE trip MODIFY COLUMN description TEXT NULL;
ALTER TABLE trip MODIFY COLUMN duration INT NULL;
ALTER TABLE trip MODIFY COLUMN time TIME NULL;
ALTER TABLE trip MODIFY COLUMN location VARCHAR(255) NULL;
ALTER TABLE trip MODIFY COLUMN images TEXT NULL;
ALTER TABLE trip MODIFY COLUMN experts TEXT NULL;
