-- 创建行程表（trip），关联用户表，存储用户旅行行程信息
CREATE TABLE "trip" (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY, -- 行程表主键ID（自增，唯一标识行程）
                        user_id BIGINT NOT NULL,                    -- 关联用户表（user）的主键id，标识行程所属用户
                        PRIMARY KEY (id),
                        CONSTRAINT idx_trip_user_id FOREIGN KEY (user_id) REFERENCES "user"(id)
);
