-- V20250927100000__Alter_table_trip_add_is_done_field.sql

ALTER TABLE trip ADD COLUMN name VARCHAR(100) NULL;
ALTER TABLE trip ADD COLUMN start VARCHAR(100) NULL;
ALTER TABLE trip ADD COLUMN description TEXT DEFAULT NULL;
ALTER TABLE trip ADD COLUMN duration VARCHAR(50) NULL;
ALTER TABLE trip ADD COLUMN time VARCHAR(50) NULL;
ALTER TABLE trip ADD COLUMN location VARCHAR(100) NULL;
ALTER TABLE trip ADD COLUMN images TEXT DEFAULT NULL;
ALTER TABLE trip ADD COLUMN experts VARCHAR(200) DEFAULT NULL;
