-- 修改trip表中多个行程字段为允许为空（原配置部分字段为NOT NULL，现统一适配非必填场景）
ALTER TABLE "trip" ALTER COLUMN name VARCHAR(100) DEFAULT NULL;
ALTER TABLE "trip" ALTER COLUMN start VARCHAR(100) DEFAULT NULL;
ALTER TABLE "trip" ALTER COLUMN description TEXT DEFAULT NULL;
ALTER TABLE "trip" ALTER COLUMN duration VARCHAR(50) DEFAULT NULL;
ALTER TABLE "trip" ALTER COLUMN time VARCHAR(50) DEFAULT NULL;
ALTER TABLE "trip" ALTER COLUMN location VARCHAR(100) DEFAULT NULL;
ALTER TABLE "trip" ALTER COLUMN images TEXT DEFAULT NULL;
ALTER TABLE "trip" ALTER COLUMN experts VARCHAR(200) DEFAULT NULL;