ALTER TABLE trip MODIFY COLUMN name VARCHAR(100) DEFAULT NULL;
ALTER TABLE trip MODIFY COLUMN start VARCHAR(100) DEFAULT NULL;
ALTER TABLE trip MODIFY COLUMN description TEXT DEFAULT NULL;
ALTER TABLE trip MODIFY COLUMN duration VARCHAR(50) DEFAULT NULL;
ALTER TABLE trip MODIFY COLUMN time VARCHAR(50) DEFAULT NULL;
ALTER TABLE trip MODIFY COLUMN location VARCHAR(100) DEFAULT NULL;
ALTER TABLE trip MODIFY COLUMN images TEXT DEFAULT NULL;
ALTER TABLE trip MODIFY COLUMN experts VARCHAR(200) DEFAULT NULL;