ALTER TABLE trip ALTER COLUMN name DROP NOT NULL;
ALTER TABLE trip ALTER COLUMN start DROP NOT NULL;
ALTER TABLE trip ALTER COLUMN description DROP NOT NULL;
ALTER TABLE trip ALTER COLUMN duration DROP NOT NULL;
ALTER TABLE trip ALTER COLUMN time DROP NOT NULL;
ALTER TABLE trip ALTER COLUMN location DROP NOT NULL;
ALTER TABLE trip ALTER COLUMN images DROP NOT NULL;
ALTER TABLE trip ALTER COLUMN experts DROP NOT NULL;