ALTER TABLE trip DROP COLUMN name;
ALTER TABLE trip ADD COLUMN name VARCHAR(100) NULL;

ALTER TABLE trip DROP COLUMN start;
ALTER TABLE trip ADD COLUMN start VARCHAR(100) NULL;

ALTER TABLE trip DROP COLUMN description;
ALTER TABLE trip ADD COLUMN description TEXT DEFAULT NULL;

ALTER TABLE trip DROP COLUMN duration;
ALTER TABLE trip ADD COLUMN duration VARCHAR(50) NULL;

ALTER TABLE trip DROP COLUMN time;
ALTER TABLE trip ADD COLUMN time VARCHAR(50) NULL;

ALTER TABLE trip DROP COLUMN location;
ALTER TABLE trip ADD COLUMN location VARCHAR(100) NULL;

ALTER TABLE trip DROP COLUMN images;
ALTER TABLE trip ADD COLUMN images TEXT DEFAULT NULL;

ALTER TABLE trip DROP COLUMN experts;
ALTER TABLE trip ADD COLUMN experts VARCHAR(200) DEFAULT NULL;
